project:
  type: website
  output-dir: docs

website:
  title: "Jun Ryu"
  favicon: favicon.png
  page-footer:
    right: |
      ![signature](/posts/signature.png){width=100} <br>
      &copy; Jun Ryu, 2023 <br>
      built with [Quarto!](https://quarto.org)
    border: false
  navbar:
    right:
      - blog.qmd
      - psets.qmd
      - misc.qmd
      - icon: github
        href: https://github.com/jryu20
      - icon: instagram
        href: https://www.instagram.com/r.yujunhee
format:
  html:
    theme: 
      light: flatly
      dark: darkly

comments:
  giscus:
    repo: jryu20/quarto


