project:
  type: website
  output-dir: docs

website:
  title: "Jun Ryu"
  page-footer:
    right: |
      ![signature](/posts/signature.png){width=100} <br>
      &copy; Jun Ryu, 2023 <br>
      built with [Quarto!](https://quarto.org)
    border: false
  navbar:
    right:
      - text: "About"
        file: about.qmd
      - text: "CV"
        file: CV.qmd
      - blog.qmd
      - psets.qmd
      - misc.qmd
      - icon: github
        href: https://github.com/jryu20
      - icon: instagram
        href: https://www.instagram.com/r.yujunhee
format:
  html:
    include-in-header:
      text: |
        <link rel="shortcut icon" type="image/x-icon" href="favicon.ico?">
    theme: 
      light: flatly
      dark: darkly

comments:
  giscus:
    repo: jryu20/jryu20.github.io


