---
comments: false
---

## Education

### University of California, Los Angeles (UCLA)

B.S. Applied Mathematics & Statistics/Data Science with a Specialization in Computing (GPA: 3.81)

Relevant Coursework: 

* Python with Applications (PIC 16A, 16B)
* Applied Numerical Methods (Math 151A, 151BH)
* Linear Algebra (Math 115A, 115B)
* Algorithms (Math 182)
* Mathematical Modeling (Math 142)
* Data Analysis and Regression (Stats 101A)
* Design and Analysis of Experiment (Stats 101B)
* Statistical Models and Data Mining (Stats 101C)
* Computational Statistics with R (Stats 102A)
* Computation and Optimization for Statistics (Stats 102B)
* Monte Carlo Methods (Stats 102C)
* Text Mining Using R (Stats 133)
* Practice of Statistical Consulting (Stats 140XP & 141XP)
* Machine Learning for Physical Sciences (AOS C111)
* Mathematics for Life Scientists (LifeSci 30A)
* Linear Models (Stats 100C)
* Introduction to Research in Statistics (Stats 143)

## Work Experience

### **Intern**, *The Stack*

* Wrote data-driven articles guided by multiple visualizations on topics relevant to the community
* Utilized JavaScript libraries (i.e. Chart.js and Leaflet) to construct visualizations

### **Undergraduate Teaching Assistant**, *Learning Assistant Program*

* Handled the logistics of the program that aims to foster collaborative and inclusive learning in STEM (science, technology, engineering and mathematics) classrooms through the use of Learning Assistants
* Implemented a JavaScript program using Google Apps Script and Google Forms to streamline the feedback process for the Learning Assistants

### **Project Associate**, *Follett Corporation*

* Implemented a program to scan for adopted books and managed inventories of educational resources

### **Reader**, *UCLA Math Department*

* Provided valuable feedback and graded students' homework based on both completion and accuracy
* Kept an organized record of over 1000 students' grades across 6 different mathematics courses

## Research

### Efficient Hyperparameter Tuning for Resource-Constrained Environments

* Optimized the performance of deep neural networks by proposing a framework for hyperparameter tuning that significantly reduces computational burden
* Developed a framework using Latin Hypercube Sampling of initial points, surrogate models such as Gaussian Processes, and early-stopping criteria, and compared it to traditional methods like grid search

## [Projects](projects.html)

### Major League Baseball (MLB) Pitcher Analysis

* Conducted an investigation to determine whether a pitcher's spin rate predicts the risk of injury as part of a consulting project
* Main Components used: **Multiple Linear Regression, Logistic Regression, Model Diagnostics**

### Stellar Classification

* Determined an astronomical object based on its spectral characteristics using classification models
* Main Components used: **Support Vector Machine, Adaptive Boosting, Artificial Neural Network**

### Effects of Various Substances on Memory

* Identified the quantitative impact of various substances on memory cognition through statistical analysis, providing valuable insights into the ongoing discourse on psychoactive substances
* Main Components used: **ANOVA, G\*Power, ggplot**

### Visualizing Zillow Homes

* Assisted users in understanding and visualizing the distribution of homes for sale on Zillow, as well as estimating home prices based on their characteristics using machine learning
* Main Components used: **Zillow API, Flask, plotly, scikit-learn, Regression Analysis**

## Relevant Experience

### **Workshop Lead**, *National Student Data Corps at UCLA*

* Led workshops related to data visualization/machine learning by creating tutorials on Google Colab

### **Research Member**, *Bruin Sports Analytics*

* Worked on a yearlong research project analyzing player trends in the NBA (National Basketball Association) using deep learning

### **Finalist**, *ASA DataFest at UCLA*

* Participated in a 48-hour data analytics hackathon looking for any trends in the dataset regarding an educational interactive software called CourseKata

<br>

## [Download My Resume](https://drive.google.com/file/d/11BME8TNm4uUD3tf8wAbjsibC-9GsjtIf/view?usp=sharing)

Click the above link to access my resume/CV.


