project:
  type: website

website:
  title: "Jun Ryu"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jryu20
      - icon: instagram
        href: https://www.instagram.com/r.yujunhee
format:
  html:
    theme: yeti
    css: styles.css



