project:
  type: website

website:
  title: "Jun Ryu"
  navbar:
    right:
      - blog.qmd
      - exercises.qmd
      - icon: github
        href: https://github.com/jryu20
      - icon: instagram
        href: https://www.instagram.com/r.yujunhee
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

comments:
  giscus:
    repo: jryu20/quarto


